version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbo_technical_test
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_PORT:5432
      - DB_HOST:localhost
      - DB_USER:postgres
      - DB_PASSWORD:password
      - DB_NAME:dbo_technical_test
      - APP_PORT:localhost:8000
      - APP_ENV:development
      - SECRET_KEY:TechnicalTest